frontend:
	@echo -e "\e[31m Creating Frontend\e[0m"
	@bash frontend.sh
##
catalouge:
	@echo -e "\e[31m Creating Catalouge\e[0m"
	@bash catalouge.sh
##
user:
	@echo creating User
	@bash user.sh
##
cart:
	@echo creating Cart
	@bash cart.sh
##
payment:
	@echo creating Payment
	@bash catalouge.sh
##
shipping:
	@echo creating Shipping
	@bash shipping.sh
##
redis:
	@echo creating Redis
	@bash redis.sh
##
myqsl:
	@echo creating MySQL
	@bash mysql.sh
##
mongodb:
	@echo -e "\e[31m Creating MongoDB\e[0m"
	@bash mongodb.sh
##
rabitmq:
	@echo creating RabitMQ
	@bash rabitmq.sh
