frontend:
	@echo creating Frontend

catalouge:
	@echo creating Catalouge

user:
	@echo creating User

cart:
	@echo creating Cart

payment:
	@echo creating Payment

shipping:
	@echo creating Shipping

redis:
	@echo creating Redis

myqsl:
	@echo creating MySQL

mongodb:
	@echo creating Mongodb

rabitmq:
	@echo creating RabitMQ





